name: product
custom: true
enable_audit: true
enable_chatter: true
enable_enhanced_lookup: true
enable_files: true
enable_search: true
field_groups:
  - group_name: 通用
  - group_name: 采购信息
icon: product
label: 产品
version: 2
